import {
  AlarmClock,
  ArrowRight,
  Banknote,
  BellOff,
  BellRing,
  Bell,
  Building2,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock,
  CloudOff,
  Compass,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Hourglass,
  House,
  Inbox,
  Info,
  KeyRound,
  Lock,
  LogOut,
  Mail,
  MailOpen,
  MessageSquareText,
  Phone,
  ReceiptText,
  RefreshCw,
  Search,
  Share2,
  TriangleAlert,
  User,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react-native';

/**
 * Bộ icon duy nhất của dự án: lucide-react-native (nét 2px, bo tròn). Không dùng emoji.
 * Gọi bằng tên ngữ nghĩa qua `<Icon name="…">` để đổi bộ icon về sau chỉ cần sửa file này.
 * Trạng thái đang chọn thể hiện bằng màu + nét đậm hơn (`strong`), không dùng bản "filled".
 */
export const icons = {
  alarm: AlarmClock,
  alertCircle: CircleAlert,
  arrowRight: ArrowRight,
  bell: Bell,
  bellOff: BellOff,
  bellRing: BellRing,
  building: Building2,
  calendar: CalendarDays,
  calendarCheck: CalendarCheck,
  card: CreditCard,
  cash: Banknote,
  check: Check,
  checkCircle: CircleCheck,
  checkDouble: CheckCheck,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  close: X,
  closeCircle: CircleX,
  compass: Compass,
  copy: Copy,
  document: FileText,
  download: Download,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  home: House,
  hourglass: Hourglass,
  inbox: Inbox,
  info: Info,
  key: KeyRound,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mailOpen: MailOpen,
  message: MessageSquareText,
  offline: CloudOff,
  phone: Phone,
  receipt: ReceiptText,
  refresh: RefreshCw,
  search: Search,
  share: Share2,
  user: User,
  wallet: Wallet,
  warning: TriangleAlert,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

/** Độ dày nét: thường 2, nhấn mạnh (tab đang chọn, icon trong ô tròn nhỏ) 2.4. */
export const iconStroke = { regular: 2, strong: 2.4 } as const;
